### ISSUE TITLE
Exception caught during firing event cpw.mods.fml.common.gameevent.PlayerEvent$PlayerLoggedInEvent

### ISSUE THREAD

**Issue by InsaneJ** [lumien231/Mod-Control#4]
We have Mod-Control setup to use a whitelist on our Cauldron server. This works well. It keeps clients out that try to connect with mods that are not on the whitelist.

Our server is running Cauldron-MCPC-Plus version git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212

In the log files we see the following error messages whenever a client tries to join the server with non-whitelisted mods: http://paste2.org/nKZCJUeC

```
[00:49:27] [Netty IO #1/INFO]: Client attempting to join with 13 mods : MapWriter@2.1.1,NotEnoughItems@1.0.3.74,Waila@1.5.7,FML@7.10.85.1236,MobiusCore@1.2.3,tfc_coremod@0.79.15,FastCraft@1.13,Forge@10.13.2.1236,TerraFirmaCraftNEIplugin@1.3.0.11,Opis@1.2.3,CodeChickenCore@1.0.4.29,terrafirmacraft@0.79.15,mcp@9.05
[00:49:27] [Netty IO #1/INFO]: Attempting connection with missing mods [Dynmap, ModControl] at CLIENT
[00:49:27] [Server thread/INFO]: [Server thread] Server side modded connection established
[00:49:27] [Server thread/INFO]: InsaneJ[/10.200.13.37:21706] logged in with entity id 533728 at ([world] -35132.249004737045, 159.62101904247183, 11303.900750939894)
[00:49:27] [Server thread/INFO]: [VanishNoPacket] InsaneJ disappeared.
[00:49:27] [Server thread/INFO]: InsaneJ lost connection: ?fYou may only join this server with ?2TerraFirmaCraft ?fand a ?2mini-map?f. Please remove all other mods from your mods directory before joining. Mods may be added to the server whitelist by request on our website ?3http://happydiggers.net ?fYou may not join this server using:?c FastCraft
[00:49:27] [Server thread/ERROR]: Exception caught during firing event cpw.mods.fml.common.gameevent.PlayerEvent$PlayerLoggedInEvent@4b1762b:
java.lang.NullPointerException
        at mcp.mobius.opis.events.PlayerTracker.getPlayerAccessLevel(PlayerTracker.java:45) ~[PlayerTracker.class:?]
        at mcp.mobius.opis.events.PlayerTracker.getPlayerAccessLevel(PlayerTracker.java:41) ~[PlayerTracker.class:?]
        at mcp.mobius.opis.network.enums.Message.canPlayerUseCommand(Message.java:130) ~[Message.class:?]
        at mcp.mobius.opis.network.PacketManager.validateAndSend(PacketManager.java:274) ~[PacketManager.class:?]
        at mcp.mobius.opis.events.PlayerTracker.onPlayerLogin(PlayerTracker.java:107) ~[PlayerTracker.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_12_PlayerTracker_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
        at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:570) [FMLCommonHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
        at net.minecraft.server.management.ServerConfigurationManager.a(ServerConfigurationManager.java:237) [oi.class:?]
        at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:173) [NetworkDispatcher.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
        at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:448) [NetworkDispatcher.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
        at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:21) [HandshakeCompletionHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
        at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11) [HandshakeCompletionHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[00:49:27] [Server thread/ERROR]: Index: 3 Listeners:
[00:49:27] [Server thread/ERROR]: 0: NORMAL
[00:49:27] [Server thread/ERROR]: 1: ASM: Forge playerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[00:49:27] [Server thread/ERROR]: 2: ASM: lumien.modcontrol.Controller@464546e playerLoggedIn(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[00:49:27] [Server thread/ERROR]: 3: ASM: INSTANCE onPlayerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[00:49:27] [Server thread/ERROR]: 4: ASM: com.bioxx.tfc.Core.Player.PlayerTracker@4dd4b008 onPlayerLoggedIn(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[00:49:27] [Server thread/ERROR]: 5: ASM: org.dynmap.forge.DynmapPlugin$PlayerTracker@60a1576e onPlayerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[00:49:27] [Server thread/ERROR]: HandshakeCompletionHandler exception
java.lang.NullPointerException
        at mcp.mobius.opis.events.PlayerTracker.getPlayerAccessLevel(PlayerTracker.java:45) ~[PlayerTracker.class:?]
        at mcp.mobius.opis.events.PlayerTracker.getPlayerAccessLevel(PlayerTracker.java:41) ~[PlayerTracker.class:?]
        at mcp.mobius.opis.network.enums.Message.canPlayerUseCommand(Message.java:130) ~[Message.class:?]
        at mcp.mobius.opis.network.PacketManager.validateAndSend(PacketManager.java:274) ~[PacketManager.class:?]
        at mcp.mobius.opis.events.PlayerTracker.onPlayerLogin(PlayerTracker.java:107) ~[PlayerTracker.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_12_PlayerTracker_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
        at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:570) ~[FMLCommonHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
        at net.minecraft.server.management.ServerConfigurationManager.a(ServerConfigurationManager.java:237) ~[oi.class:?]
        at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:173) ~[NetworkDispatcher.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
        at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:448) ~[NetworkDispatcher.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
        at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:21) ~[HandshakeCompletionHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
        at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11) ~[HandshakeCompletionHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[00:49:27] [Server thread/ERROR]: There was a critical exception handling a packet on channel FML
java.lang.NullPointerException
        at mcp.mobius.opis.events.PlayerTracker.getPlayerAccessLevel(PlayerTracker.java:45) ~[PlayerTracker.class:?]
        at mcp.mobius.opis.events.PlayerTracker.getPlayerAccessLevel(PlayerTracker.java:41) ~[PlayerTracker.class:?]
        at mcp.mobius.opis.network.enums.Message.canPlayerUseCommand(Message.java:130) ~[Message.class:?]
        at mcp.mobius.opis.network.PacketManager.validateAndSend(PacketManager.java:274) ~[PacketManager.class:?]
        at mcp.mobius.opis.events.PlayerTracker.onPlayerLogin(PlayerTracker.java:107) ~[PlayerTracker.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_12_PlayerTracker_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
        at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:570) ~[FMLCommonHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
        at net.minecraft.server.management.ServerConfigurationManager.a(ServerConfigurationManager.java:237) ~[oi.class:?]
        at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:173) ~[NetworkDispatcher.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
        at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:448) ~[NetworkDispatcher.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
        at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:21) ~[HandshakeCompletionHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
        at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11) ~[HandshakeCompletionHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[00:49:27] [Server thread/WARN]: Failed to handle packet for /10.200.13.37:21706
java.lang.NullPointerException
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:101) ~[FMLProxyPacket.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
```

**Comment by lumien231** [comment]
Does this also hapen without opis installed?

**Comment by InsaneJ** [comment]
No, without Opis a blocked connection looks like this:

```
[15:58:41] [Netty IO #0/INFO]: Client attempting to join with 13 mods : MapWriter@2.1.1,NotEnoughItems@1.0.3.74,Waila@1.5.7,FML@7.10.85.1236,MobiusCore@1.2.3,tfc_coremod@0.79.15,FastCraft@1.13,Forge@10.13.2.1236,TerraFirmaCraftNEIplugin@1.3.0.11,Opis@1.2.3,CodeChickenCore@1.0.4.29,terrafirmacraft@0.79.15,mcp@9.05
[15:58:41] [Netty IO #0/INFO]: Attempting connection with missing mods [Dynmap, ModControl] at CLIENT
[15:58:41] [Server thread/INFO]: [Server thread] Server side modded connection established
[15:58:41] [Server thread/INFO]: InsaneJ[/10.200.13.37:2003] logged in with entity id 464254 at ([hardcore] -22.283025830447592, 148.0, -5701.8017457118185)
[15:58:41] [Server thread/INFO]: [VanishNoPacket] InsaneJ disappeared.
[15:58:41] [Server thread/INFO]: InsaneJ lost connection: ?fYou may only join this server with ?2TerraFirmaCraft ?fand a ?2mini-map?f. Please remove all other mods from your mods directory before joining. Mods may be added to the server whitelist by request on our website ?3http://happydiggers.net ?fYou may not join this server using:?c FastCraft
```

No errors like you would expect.

**Comment by lumien231** [comment]
Try this with vanilla forge.

**Comment by InsaneJ** [comment]
With forge-1.7.10-10.13.2.1286-universal this does not seem to happen.
